server:
  port: 666
spring:
  profiles:
    active: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5466/eMagazine_db
    username: admin_mag
    password: 123

  jpa:
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-bean-definition-overriding: true

  flyway:
    locations: filesystem:./eMagazine-db/src/main/resources/db

  rabbitmq:
    host: localhost
    port: 5672

logging:
  level:
    web: trace
    org.springframework.web: trace

emagazine:
  app:
    version: @project.version@