server:
  port: 666
spring:
  profiles:
    active: development
  r2dbc:
#    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://localhost:5466/eMagazine_db
    username: admin_mag
    password: 123
    pool:
      enabled: true
      initial-size: 50 # первоначальная ёмкость пула подключений к БД
      max-idle-time: 5m # таймаут по истечении которого соединение удаляется из пула
      max-size: 200 # максимальная ёмкость пула подключений к БД
      data:
        r2dbc:
          repositories:
            enabled: true

  jpa:
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-bean-definition-overriding: true

  flyway:
    locations: filesystem:./eMagazine-db/src/main/resources/db

  rabbitmq:
    host: localhost
    port: 5672

logging:
  level:
    web: trace
    org.springframework.web: trace

emagazine:
  app:
    version: @project.version@